### ISSUE TITLE
Gulp not passing tests and linting

### ISSUE THREAD

**Issue by chuckh** [PolymerElements/generator-polymer-init-custom-build#3]
When running `gulp` getting the follow results:

```
RocketMan:generator-polymer-init-custom-build chuckh$ gulp
[14:47:24] Using gulpfile ~/DevPolymerLocal/custom-build/generator-polymer-init-custom-build/gulpfile.js
[14:47:24] Starting 'static'...
[14:47:24] Starting 'pre-test'...
[14:47:25] Finished 'pre-test' after 1.3 s
[14:47:25] Starting 'test'...


  generator-polymer-init-custom-build:app
    1) creates files


  0 passing (214ms)
  1 failing

  1) generator-polymer-init-custom-build:app creates files:

      AssertionError: dummyfile.txt, no such file or directory
      + expected - actual

      -false
      +true

      at node_modules/yeoman-assert/index.js:46:12
      at Array.forEach (native)
      at Function.assert.file (node_modules/yeoman-assert/index.js:44:8)
      at Context.<anonymous> (test/app.js:24:12)



--------------------------|----------|----------|----------|----------|----------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
--------------------------|----------|----------|----------|----------|----------------|
 app/                     |    27.78 |      100 |      100 |    27.78 |                |
  gulpfile.js             |        0 |      100 |      100 |        0 |... 72,77,85,93 |
  index.js                |      100 |      100 |      100 |      100 |                |
 app/polymer-starter-kit/ |        0 |      100 |      100 |        0 |                |
  service-worker.js       |        0 |      100 |      100 |        0 |             10 |
  sw-precache-config.js   |        0 |      100 |      100 |        0 |             10 |
--------------------------|----------|----------|----------|----------|----------------|
All files                 |    26.32 |      100 |      100 |    26.32 |                |
--------------------------|----------|----------|----------|----------|----------------|


=============================== Coverage summary ===============================
Statements   : 26.32% ( 10/38 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 2/2 )
Lines        : 26.32% ( 10/38 )
================================================================================
[14:47:26] 'test' errored after 816 ms
[14:47:26] Error in plugin 'gulp-mocha'
Message:
    1 test failed.
[14:47:27]
/Users/chuckh/DevPolymerLocal/custom-build/generator-polymer-init-custom-build/generators/app/gulpfile.js
  19:8   error  'logging' is defined but never used                     no-unused-vars
  38:32  error  Unexpected parentheses around single function argument  arrow-parens
  59:10  error  'bundledPhase' is defined but never used                no-unused-vars
  64:10  error  'unbundledPhase' is defined but never used              no-unused-vars
  73:37  error  Unexpected trailing comma                               comma-dangle
  77:10  error  'unbundledPostProcessing' is defined but never used     no-unused-vars
  81:44  error  Unexpected trailing comma                               comma-dangle
  85:10  error  'bundledPostProcessing' is defined but never used       no-unused-vars
  89:19  error  Unexpected trailing comma                               comma-dangle

/Users/chuckh/DevPolymerLocal/custom-build/generator-polymer-init-custom-build/generators/app/index.js
   3:7   error  'chalk' is defined but never used  no-unused-vars
   4:7   error  'yosay' is defined but never used  no-unused-vars
  17:54  error  Unexpected trailing comma          comma-dangle

✖ 12 problems (12 errors, 0 warnings)

[14:47:27] 'static' errored after 3.59 s
[14:47:27] ESLintError in plugin 'gulp-eslint'
Message:
    Failed with 12 errors
```

**Comment by chuckh** [comment]
If you try to fix some errors such as `38:32  error  Unexpected parentheses around single function argument  arrow-parens` breaks `gulp` command. But others we can fix.

**Comment by chuckh** [comment]
PRs #17 and #18 fixes these errors.
