### ISSUE TITLE
gulp build, stops without errors

### ISSUE THREAD

**Issue by andimclean** [PolymerElements/generator-polymer-init-custom-build#64]
Having copied the gulpfile.js from this project for my polymer app, and installed the necessary npm modules.

on running gulp build I get : 
[22:32:00] Using gulpfile ~/development/wawm/gulpfile.js
[22:32:00] Starting 'build'...
Deleting build/gulp directory...
Analyzing build dependencies...

then it pauses for a while then the command prompt returns
The images and the bower components have been copied, but none of my scripts.

No errors are shown.Any hints on what I'm doing wrong.

**Comment by andimclean** [comment]
I dbl checked package.json and noted that I was using a different version of gulp,
Upon chanigng to the same one in the package.json
I now get:
[22:41:50] The following tasks did not complete: build
[22:41:50] Did you forget to signal async completion?

I'm using node 7.6.0 and npm 4.1.2

**Comment by stramel** [comment]
@andimclean which gulp version are you using? You should be using gulp4 installed using `npm i -g gulpjs/gulp#4.0`

**Comment by andimclean** [comment]
I was using an older version of gulp, which caused the build just to stop.

Now I get the error I mentioned above.

**Comment by robdodson** [comment]
hmmmmmm @FredKSchott any ideas?

**Comment by andimclean** [comment]
I ran polymer lint, fixed a few missing properties and now the only errors I get are in the bower_components.

Polymer build run, but warns of some syntax errors:

polymer build
info:    Preparing build...
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/wawm-app.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 29,
     col: 99,
     pos: 641,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/addable-fab.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 40,
     col: 71,
     pos: 1296,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/animal-details.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 38,
     col: 23,
     pos: 1160,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at expect_token (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2115:9)\n    at expect (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2118:36)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2691:13)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:35)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/animal-image.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 16,
     col: 24,
     pos: 424,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at expect_token (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2115:9)\n    at expect (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2118:36)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2691:13)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2621:35)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/edit-animal.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 34,
     col: 43,
     pos: 995,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/key-value-list.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 24,
     col: 73,
     pos: 750,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/obj-array.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: name (Objarray)',
     filename: 0,
     line: 5,
     col: 18,
     pos: 69,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at semicolon (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2128:56)\n    at simple_statement (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2319:73)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2188:19)\n    at eval (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2141:24)\n    at block_ (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2434:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/printer-popup.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: punc ())',
     filename: 0,
     line: 36,
     col: 32,
     pos: 2005,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2623:13)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/users-details.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 47,
     col: 79,
     pos: 1599,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
warn:    Unable to optimize .js file /home/andi/development/wawm/src/wawm-app/elements/vetcode-behaviour.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 7,
     col: 23,
     pos: 303,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }
Ignoring duplicate element definition: app-location
Ignoring duplicate element definition: firebase-app
Ignoring duplicate element definition: firebase-auth
Ignoring duplicate element definition: iron-pages
Ignoring duplicate element definition: custom-style
Ignoring duplicate element definition: dom-template
Ignoring duplicate element definition: dom-repeat
Ignoring duplicate element definition: array-selector
Ignoring duplicate element definition: dom-if
Ignoring duplicate element definition: dom-bind
Ignoring duplicate element definition: iron-location
Ignoring duplicate element definition: iron-query-params
Ignoring duplicate element definition: firebase-document
Ignoring duplicate element definition: iron-iconset-svg
Ignoring duplicate element definition: paper-icon-button
Ignoring duplicate element definition: iron-meta
Ignoring duplicate element definition: iron-meta-query
Ignoring duplicate element definition: iron-icon
Ignoring duplicate element definition: paper-ripple
warn:    Unable to optimize .js file /home/andi/development/wawm/bower_components/paper-datatable/paper-datatable.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected token: operator (>)',
     filename: 0,
     line: 195,
     col: 31,
     pos: 4716,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)\n    at js_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1555:11)\n    at croak (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2094:9)\n    at token_error (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2102:9)\n    at unexpected (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2108:9)\n    at expr_atom (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2635:9)\n    at maybe_unary (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2797:19)\n    at expr_ops (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2832:24)\n    at maybe_conditional (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2837:20)\n    at maybe_assign (eval at <anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2861:20)' } }

**Comment by robdodson** [comment]
It looks like `wawm-app.html` may contain some busted js. Can you share a gist of that file?

**Comment by andimclean** [comment]
https://gist.github.com/andimclean/a4a2b761160e7ac5388afee57d5800ed

**Comment by andimclean** [comment]
any ideas on this issue?

**Comment by robdodson** [comment]
Hm not sure. Is your Lazy util written in es6?
