### ISSUE TITLE
README instructions don't work

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/generator-polymer-init-custom-build#84]
```
08:36:33 ~$ mkdir my-app
08:36:38 ~$ cd my-app
08:36:38 ~/my-app$ polymer init polymer-starter-kit-custom-build
info:    Running template polymer-init-polymer-starter-kit-custom-build:app...
error:   Template polymer-init-polymer-starter-kit-custom-build:app not found
error:   cli runtime exception: Error: Template polymer-init-polymer-starter-kit-custom-build:app not found
error:   Error: Template polymer-init-polymer-starter-kit-custom-build:app not found
    at Object.<anonymous> (/home/davidmaxwaterman/.nvm/versions/node/v6.11.4/lib/node_modules/polymer-cli/lib/init/init.js:220:19)
    at next (native)
    at fulfilled (/home/davidmaxwaterman/.nvm/versions/node/v6.11.4/lib/node_modules/polymer-cli/lib/init/init.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
08:36:42 ~/my-app$ 
```

According to the polymer-cli help, it *should* work if you use the `--name` parameter, but that also doesn't work:

```
08:37:54 ~/my-app$ polymer init --name polymer-starter-kit-custom-build
info:    Running template polymer-init-polymer-starter-kit-custom-build:app...
error:   Template polymer-init-polymer-starter-kit-custom-build:app not found
error:   cli runtime exception: Error: Template polymer-init-polymer-starter-kit-custom-build:app not found
error:   Error: Template polymer-init-polymer-starter-kit-custom-build:app not found
    at Object.<anonymous> (/home/davidmaxwaterman/.nvm/versions/node/v6.11.4/lib/node_modules/polymer-cli/lib/init/init.js:220:19)
    at next (native)
    at fulfilled (/home/davidmaxwaterman/.nvm/versions/node/v6.11.4/lib/node_modules/polymer-cli/lib/init/init.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

It does seem to work if I just run `polymer init` and select it from the menu though.

08:38:05 ~/my-app$ polymer --version
1.5.7

**Comment by abdonrd** [comment]
It's a bit strange.

* It doesn't work: `polymer init polymer-starter-kit-custom-build`
* It works: `polymer init` & select `polymer-starter-kit-custom-build`
* It works: `polymer init custom-build`

***

<img width="699" alt="screen shot 2017-10-19 at 11 15 19" src="https://user-images.githubusercontent.com/1007051/31763573-f1e33dea-b4be-11e7-9c8f-288028d55147.png">

**Comment by abdonrd** [comment]
@FredKSchott It seems somewhat related to the CLI. You know?

**Comment by stramel** [comment]
@abdonrd it looks like just a labelling mismatch. The CLI looks for `generator-polymer-init-` when you pass an argument to `polymer init`. When it generates the list it is pulling the title from the generator's package.json 
https://github.com/PolymerElements/generator-polymer-init-custom-build/blob/74f92ffed07d3d4c582805918a55b74e6d21dab2/generators/app/package.json#L2

**Comment by ghost** [comment]
README instructions don't work
